### ISSUE TITLE
Monaco Editor 'intellisense'

### ISSUE THREAD

**Issue by theZiggurat** [theZiggurat/gputoy#28]
### Current Implementation
The spec is scraped off [wgsl docs](https://www.w3.org/TR/WGSL/) with a python script. It is then converted to a JavaScript object containing the necessary data to show up in Monaco as a completion suggestion. Here is an example of a completion suggestion:
```
{
    "detail": "abs(e: T) -> T where: T is f32 or vecN<f32>",
    "documentation": "Returns the absolute value of e (e.g. e with a positive sign bit). Component-wise when T is a vector.\n (GLSLstd450Fabs)",
    "label": "abs",
    "insertText": "abs(${1})",
    "insertTextRules": 4,
  },
```
This should be automated in the future so any changes to the spec are reflected within the application. The intellisense system should also support variables generated by the user or site. 

### Enhancements

- [ ] Provide completions for built-in shader types and keywords. 
- [ ] Provide completions for user created variables and structs. For instance, if the user creates a uniform called `c`, `c` should appear in completion suggestions.
- [ ] Provide completions for gputoy provided uniforms.
