### ISSUE TITLE
pages/docs

### ISSUE THREAD

**Issue by theZiggurat** [theZiggurat/gputoy#30]
A page where users can browse documentation on shader functions, editor actions, and common techniques.

- [ ] shader functions: Comprehensive list of wgsl/glsl functions pulled from the docs. Eventually, each function doc could have a corresponding embeddable project showcasing an example use or use-case of the function. 
- [ ] editor actions: How to accomplish various tasks in the editor. This will most likely need some sort of touring library. 
- [ ] common techniques: this will require collaboration with users and skilled creators.
